#!/usr/bin/env bash

OLD_HOSTNAME=`cat /etc/hostname`
if [ "$OLD_HOSTNAME" == "changeit" ]; then
    PATH_TO_GENHOST=/usr/sbin/genhost
    export GENHOST_DOMAIN=`dnsdomainname`
    NEW_HOSTNAME=`$PATH_TO_GENHOST 1`
    echo $NEW_HOSTNAME > /etc/hostname
    hostname $NEW_HOSTNAME
    /etc/init.d/networking restart
fi
